/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://fqzd4yogh5cgtearygajlejtqi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vxckc6tjifduvbzj67mjd6eso4",
    "aws_cognito_identity_pool_id": "us-east-1:26f16227-e1b2-4999-a7f4-b32d92d2ccd5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_woVc85BcH",
    "aws_user_pools_web_client_id": "6gu77vplcr4qmd68jqqpumjgm",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 10,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-amplify74c2dc8c21234-staging-235546-deployment",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
